### ISSUE TITLE
[BUG] Link failure in fltk::window::DoubleWindow::platform_hide when building without wayland

### ISSUE THREAD

**Issue by thorio** [fltk-rs/fltk-rs#1576]
## Describe the bug
Trying to build without the `use-wayland` feature breaks when using [`fltk::window::DoubleWindow::platform_hide`][platform_hide] anywhere in the program. It seems to me the wayland block in `platform_hide` should be excluded from compilation unless compiling with wayland enabled.

[platform_hide]: https://github.com/fltk-rs/fltk-rs/blob/ebe002b930cecc2b090185551c3e2f4300fe766f/fltk/src/window.rs#L460-L470

<details>
<summary><code>cargo build</code> output</summary>

```txt
vscode ➜ /workspaces/testproject (master) $ cargo build
   Compiling testproject v0.1.0 (/workspaces/testproject)
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/usr/local/rustup/toolchains/1.79.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/vscode/vscode-server/bin/linux-x64/eaa41d57266683296de7d118f574d0c2652e1fc4/bin/remote-cli:/usr/local/cargo/bin:/usr/local/cargo/bin:/usr/local/cargo/bin:/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/vscode/.local/bin" VSLANG="1033" "cc" "-m64" "/tmp/rustcF8X75O/symbols.o" "/workspaces/testproject/target/debug/deps/testproject-753e9220d83f7926.2kxg9ft0u3hwrcv6.rcgu.o" "/workspaces/testproject/target/debug/deps/testproject-753e9220d83f7926.34ij9bns9u76lggm.rcgu.o" "/workspaces/testproject/target/debug/deps/testproject-753e9220d83f7926.3ugtn5nysq3avvkg.rcgu.o" "/workspaces/testproject/target/debug/deps/testproject-753e9220d83f7926.4jw7t117p849njxq.rcgu.o" "/workspaces/testproject/target/debug/deps/testproject-753e9220d83f7926.4uxkcziikdob2beq.rcgu.o" "/workspaces/testproject/target/debug/deps/testproject-753e9220d83f7926.ibcqxmpuxoqk0aw.rcgu.o" "-Wl,--as-needed" "-L" "/workspaces/testproject/target/debug/deps" "-L" "/workspaces/testproject/target/debug/build/fltk-sys-5f341043438df983/out/build" "-L" "/workspaces/testproject/target/debug/build/fltk-sys-5f341043438df983/out/build/Release" "-L" "/workspaces/testproject/target/debug/build/fltk-sys-5f341043438df983/out/lib" "-L" "/workspaces/testproject/target/debug/build/fltk-sys-5f341043438df983/out/lib64" "-L" "/workspaces/testproject/target/debug/build/fltk-sys-5f341043438df983/out/lib/Release" "-L" "/workspaces/testproject/target/debug/build/fltk-sys-5f341043438df983/out/lib64/Release" "-L" "/usr/local/rustup/toolchains/1.79.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/workspaces/testproject/target/debug/deps/libfltk-7589dfcf9be7dc5a.rlib" "/workspaces/testproject/target/debug/deps/libttf_parser-dc39c0bcee6e8284.rlib" "/workspaces/testproject/target/debug/deps/libcrossbeam_channel-b950cfaf4a8219eb.rlib" "/workspaces/testproject/target/debug/deps/libcrossbeam_utils-110cd5326d35c5d9.rlib" "/workspaces/testproject/target/debug/deps/libbitflags-1be65c5f62df8a3d.rlib" "/workspaces/testproject/target/debug/deps/libonce_cell-0152a482d713e481.rlib" "/workspaces/testproject/target/debug/deps/libfltk_sys-c2515c79e5f8f14c.rlib" "/usr/local/rustup/toolchains/1.79.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-d5189b81a4fa4d36.rlib" "/usr/local/rustup/toolchains/1.79.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-6a4779412a873200.rlib" "/usr/local/rustup/toolchains/1.79.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-c88c426dd6780435.rlib" "/usr/local/rustup/toolchains/1.79.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-e74540b31113a555.rlib" "/usr/local/rustup/toolchains/1.79.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-8751b61bd13c15cf.rlib" "/usr/local/rustup/toolchains/1.79.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-a8b99dba9f449259.rlib" "/usr/local/rustup/toolchains/1.79.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-f0068d76172a0372.rlib" "/usr/local/rustup/toolchains/1.79.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-c16dfaf47799564e.rlib" "/usr/local/rustup/toolchains/1.79.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-bfa26dd63e299db5.rlib" "/usr/local/rustup/toolchains/1.79.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-75a2330a693e738f.rlib" "/usr/local/rustup/toolchains/1.79.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-76779dce1f7ab63d.rlib" "/usr/local/rustup/toolchains/1.79.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-01c5cc588623cb35.rlib" "/usr/local/rustup/toolchains/1.79.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-07bb9745ec737292.rlib" "/usr/local/rustup/toolchains/1.79.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-6eacdcc91004cefb.rlib" "/usr/local/rustup/toolchains/1.79.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-ae2488b58226c836.rlib" "/usr/local/rustup/toolchains/1.79.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-52acaddcaaba04c6.rlib" "/usr/local/rustup/toolchains/1.79.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-326b78eac9ecd050.rlib" "/usr/local/rustup/toolchains/1.79.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-307ebf19f0f13d30.rlib" "/usr/local/rustup/toolchains/1.79.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-d9076ee5964191bf.rlib" "-Wl,-Bdynamic" "-lpthread" "-lX11" "-lXext" "-lXinerama" "-lXcursor" "-lXrender" "-lXfixes" "-lXft" "-lfontconfig" "-lpango-1.0" "-lpangoxft-1.0" "-lgobject-2.0" "-lcairo" "-lpangocairo-1.0" "-lsupc++" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/usr/local/rustup/toolchains/1.79.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/workspaces/testproject/target/debug/deps/testproject-753e9220d83f7926" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
  = note: /usr/bin/ld: /workspaces/testproject/target/debug/deps/libfltk-7589dfcf9be7dc5a.rlib(fltk-7589dfcf9be7dc5a.fltk.ba04757438741360-cgu.04.rcgu.o): in function `fltk::window::DoubleWindow::platform_hide':
          /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/fltk-1.4.33/src/window.rs:463: undefined reference to `wl_proxy_marshal'
          /usr/bin/ld: /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/fltk-1.4.33/src/window.rs:470: undefined reference to `wl_proxy_marshal'
          collect2: error: ld returned 1 exit status
          
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-lib)

error: could not compile `testproject` (bin "testproject") due to 1 previous error
```
</details>

## To Reproduce
```toml
[package]
name = "testproject"
version = "0.1.0"
edition = "2021"

[dependencies]
fltk = { version = "1.4.33", features = ["fltk-bundled"] }
```

```rust
use fltk::window::Window;

fn main() {
    let wind = Window::default();

    wind.platform_hide();
}
```

## Expected behavior
The program should compile without referencing wayland libraries.

## Desktop info
 - OS: `mcr.microsoft.com/devcontainers/rust:1-bookworm` Docker image (Debian bookworm); running on Linux kernel 6.10.4-arch2-1
 - Version 1.4.33
 - Display server: X11

**Comment by MoAlyousef** [comment]
Thanks for the report. I’ll check this tonight.

**Comment by MoAlyousef** [comment]
Can you try with the latest master:
```toml
[dependencies]
fltk = "^1.4"

[patch.crates-io]
fltk = { git = "https://github.com/fltk-rs/fltk-rs" }
```
Note that this is not compatible with fltk-bundled yet (not until a new bundle is released).

**Comment by thorio** [comment]
It builds and runs fine when targeting X11 only, but when built _with_ wayland support the `platform_hide` call doesn't do anything on X11 (I can't test wayland at the moment)

There was also some weird segfaulting going on when calling external binaries on the 1.4.33 version _with wayland support_ on X11, that seems to be gone on latest master. I'll test this further in the coming days and open an issue if appropriate.

**Comment by MoAlyousef** [comment]
I have pushed a fix for targeting X11 with use-wayland. 
I don’t think platform_hide() can be made to work with wayland since it would require access to things internal to FLTK itself like the wayland buffer, the decorator’s (libdecor) surface etc.

**Comment by thorio** [comment]
The segfaulting issue only happens on v1.4.32 with `use-wayland` feature, running on X11, when calling `platform_hide`. It's fixed in v1.4.33 and current master.

I've tested the current master with `use-wayland` on/off, running on X11, both compile and run fine with `platform_hide` now.

I couldn't get regular hide/show to work previously because I needed to still receive messages on to channels. I managed to get it to work now by doing this:
```rust
fn run_event_loop(&mut self, receiver: &RReceiver<FrontendMessageNe>) -> FrontendExitStatus {
	loop {
		if let Err(e) = fltk::app::wait_for(0.005) {
			// TODO: handle X11 signals?
			log::error!("fltk wait_for error: {e}");
		}

		// this doesn't seem to trigger when killing the X window from the WM
		if fltk::app::should_program_quit() {
			// custom enum, not the fltk Event
			self.ui.sender.send(Event::Exit);
		}

		self.forward_frontend_messages(receiver);

		if let Some(exit) = self.receive_event() {
			fltk::app::quit();

			// give fltk a chance to clean up, not sure if this is needed
			fltk::app::wait();

			return exit;
		}
	}
}
```
